# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: 修复 Fixs
      labels:
        - fix
        - bug
    - title: 重大更新 Feats
      labels:
        - feat
        - enhancement
    - title: 日常更新 Chores
      labels:
        - chore
        - deploy
    - title: 其他更新 Other Changes
      labels:
        - "*"
